server:
  port: ${PORT:8080}
  auth:
    provider: http://localhost:9000
  ssl:
    key-store-type: PKCS12
    key-store: ${KEY_PATH:main/src/main/resources/baeldung.p12}
    key-store-password: aXaghasftasdl
    key-alias: baeldung
    enabled: false
spring:
  gateway:
    url: ${GATEWAY_URL:localhost:8080}
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  routing:
    key: routing-key.1
  routing2:
    key: routing-key.2
  exchange:
    name: chess-moves
  queue:
    name: chess-moves.1
  queue2:
    name: chess-moves.2